import { VMICWebRTCStats } from "@/types/webrtc-stats";

export type RemoteAudioCallback = (
  participantId: string,
  stream: MediaStream
) => void;

export type ConnectionStateCallback = (
  participantId: string,
  state: RTCPeerConnectionState
) => void;

export type WebRTCStatsCallback = (
  stats: VMICWebRTCStats
) => void;


export class VMICHostWebRTC {

  private peerConnections =
    new Map<string, RTCPeerConnection>();

  private statsCallback: WebRTCStatsCallback | null = null;

  private statsTimer: ReturnType<typeof setInterval> | null = null;

  constructor(
    private onIceCandidate?: (
      participantId: string,
      candidate: RTCIceCandidate
    ) => void,

    private onRemoteAudio?: RemoteAudioCallback,

    private onConnectionStateChange?: ConnectionStateCallback,

    onStats?: WebRTCStatsCallback
  ) {
    if (onStats) {
      this.statsCallback = onStats;
    }
  }

  setStatsCallback(callback: WebRTCStatsCallback) {
    this.statsCallback = callback;
  }

  startStatsMonitoring(intervalMs = 1000) {
    if (this.statsTimer !== null) return;

    this.statsTimer = setInterval(async () => {
      for (const [participantId, peerConnection] of this.peerConnections) {
        try {
          await this.collectStats(participantId, peerConnection);
        } catch (error) {
          console.error(`[WebRTC Stats] Error for ${participantId}:`, error);
        }
      }
    }, intervalMs);
  }

  stopStatsMonitoring() {
    if (this.statsTimer !== null) {
      clearInterval(this.statsTimer);
      this.statsTimer = null;
    }
  }

  async collectStats(
    participantId: string,
    peerConnection: RTCPeerConnection
  ) {
    const report = await peerConnection.getStats();

    let packetsReceived = 0;
    let packetsLost = 0;
    let jitter = 0;
    let bytesReceived = 0;
    let roundTripTime: number | null = null;

    report.forEach((stat) => {
      if (stat.type === "inbound-rtp" && stat.kind === "audio") {
        packetsReceived = stat.packetsReceived ?? 0;
        packetsLost = stat.packetsLost ?? 0;
        jitter = (stat.jitter ?? 0) * 1000; // convert to ms
        bytesReceived = stat.bytesReceived ?? 0;
      }

      if (stat.type === "candidate-pair" && stat.state === "succeeded") {
        if (stat.currentRoundTripTime !== undefined) {
          roundTripTime = stat.currentRoundTripTime * 1000; // convert to ms
        }
      }
    });

    if (this.statsCallback) {
      this.statsCallback({
        participantId,
        connectionState: peerConnection.connectionState,
        iceConnectionState: peerConnection.iceConnectionState,
        packetsReceived,
        packetsLost,
        jitter,
        bytesReceived,
        roundTripTime,
        timestamp: Date.now(),
      });
    }
  }

  async handleOffer(
    participantId: string,
    sdp: string
  ) {

    console.log(
      `[Host WebRTC] Offer from ${participantId}`
    );

    const peerConnection =
      new RTCPeerConnection({
        // Single STUN server as fallback; LAN candidates will be preferred
        iceServers: [
          { urls: "stun:stun.l.google.com:19302" },
        ],
        // Pre-allocate ICE candidate for faster gathering on LAN
        iceCandidatePoolSize: 1,
      });

    this.peerConnections.set(
      participantId,
      peerConnection
    );


    /*
     * ICE candidate generated by host
     */

    peerConnection.onicecandidate =
      (event) => {

        if (
          event.candidate &&
          this.onIceCandidate
        ) {

          this.onIceCandidate(
            participantId,
            event.candidate
          );

        }

      };


    /*
     * Connection state
     */

    peerConnection.onconnectionstatechange =
      () => {

        const state =
          peerConnection.connectionState;

        console.log(
          `[Host WebRTC] ${participantId} connection:`,
          state
        );

        if (this.onConnectionStateChange) {
          this.onConnectionStateChange(
            participantId,
            state
          );
        }

      };


    /*
     * ICE state
     */

    peerConnection.oniceconnectionstatechange =
      () => {

        console.log(
          `[Host WebRTC] ${participantId} ICE:`,
          peerConnection.iceConnectionState
        );

      };


    /*
     * THIS IS THE IMPORTANT PART
     */

    peerConnection.ontrack =
      (event) => {

        console.log(
          `[Host WebRTC] Audio track received from ${participantId}`
        );

        const stream =
          event.streams[0];

        if (!stream) {
          console.warn(
            "No MediaStream attached to track"
          );

          return;
        }

        console.log(
          "[Host WebRTC] Remote stream:",
          stream
        );

        if (this.onRemoteAudio) {

          this.onRemoteAudio(
            participantId,
            stream
          );

        }

      };


    /*
     * Apply phone's SDP offer
     */

    await peerConnection.setRemoteDescription(
      new RTCSessionDescription({
        type: "offer",
        sdp,
      })
    );


    /*
     * Create host answer
     */

    const answer =
      await peerConnection.createAnswer();


    /*
     * Set host's local SDP
     */

    await peerConnection.setLocalDescription(
      answer
    );

    // Auto start stats monitoring when first peer connects
    this.startStatsMonitoring();

    return answer;

  }


  async addIceCandidate(
    participantId: string,
    candidate: RTCIceCandidateInit
  ) {

    const peerConnection =
      this.peerConnections.get(
        participantId
      );

    if (!peerConnection) {

      console.warn(
        `No peer connection for ${participantId}`
      );

      return;
    }

    await peerConnection.addIceCandidate(
      new RTCIceCandidate(candidate)
    );

  }


  getPeerConnection(
    participantId: string
  ) {

    return this.peerConnections.get(
      participantId
    );

  }


  closeParticipant(
    participantId: string
  ) {

    const connection =
      this.peerConnections.get(
        participantId
      );

    connection?.close();

    this.peerConnections.delete(
      participantId
    );

    if (this.peerConnections.size === 0) {
      this.stopStatsMonitoring();
    }

  }

}
